### ISSUE TITLE
کێشەی هەس

### ISSUE THREAD

**Issue by qezwan** [dolanskurd/Dictio#2]
کاک دۆلانی ئازیز دەستخۆش
من پێشتر باسی دیکتۆم لەگەڵیان کرد بڕاستی کێشەی زۆرە، زۆر وشەی ئینگلیزی تێدایە کە جودا نەکراوەتەوە، بۆیە زۆر وشەی هەر بە مانای گشتی باس دەکرێت کەئەمە بەکارهێنەر سەرشێواو دەکا.
سپاس بۆ کارە جوانەکانت

**Comment by 0xdolan** [comment]
سوپاست دەکەم کاکە گیان. وەڵڵا من لەبەر ڕێزگرتن لە ماندووبوونیان، داتاکانانم وەرنەگرتووە و هەر بە ئۆنلاین کاری پێدەکەین بەڵام لەناو GoldennDict. جا نازانم مەبەستت کێشە لە وشە و ماناکانی دیکتیۆ بوو بە گشتی یان کێشە لە ئەو فایلەی من درووستم کردووە؟ ئەگەر کێشە لە دیکتیۆ بێت، ئەوە من لێی بێبەریم 😁🤷🏻‍♂️ ئەگەرنا کێشە لە فایلەکەی منە، با لەخزمەتدا بم.
